### PR TITLE
ec affine from/to coords

### PR DESCRIPTION
**Pull request by adria0**
In order to help to custom serialization/deserialization, added  `try_from_coordinates` / `try_to_coordinates` functions in affines generation macro.

### CODE REVIEW

**Comment by shamatar** [comment]
@adria0 I'd propose to have two functions to make a point from coordinates:
- one that does on-curve check and subgroup check
- one that does no checks

It follows the API of conversion from encoded point and is reasonable set: one gives no guarantees, one makes all the checks.

Sincerely, Alexander

**Comment by adria0** [comment]
@shamatar, absolutely agree,

About having a method without checking, my proposal is a method called
`unsafe fn from_coordinates_unchecked(x: $basefield, y: $basefield) -> $affine`.

About the subgroup checking,  it seems that the `bls12_381::is_in_correct_subgroup_assuming_on_curve()` code will also work for `bn256`?

**Comment by poma** [comment]
Looks like #6 includes all changes from this PR (with different function names). Probably this one can be closed.

**Comment by shamatar** [comment]
Should be exposed in #7

**Pull request closed without merging**
